# Generated by Django 3.2.9 on 2021-11-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
