# Generated by Django 3.2.8 on 2021-10-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votebutton',
            name='messages',
            field=models.CharField(default='message', max_length=256),
        ),
    ]
