# Generated by Django 3.2.9 on 2021-11-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_publication_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='rating',
        ),
        migrations.AddField(
            model_name='publication',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
