# Generated by Django 3.2.9 on 2021-12-06 01:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211206_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
