# Generated by Django 3.2.9 on 2021-11-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211030_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votebutton',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
