# Generated by Django 3.2.9 on 2021-11-10 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20211110_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPublicationRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Not bad'), (4, 'Good'), (5, 'Amazing')])),
                ('comment', models.TextField(max_length=3000)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('like', models.BooleanField(default=False)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
