# Generated by Django 3.2.9 on 2021-12-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211206_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='images',
        ),
    ]
