# Generated by Django 3.2.9 on 2021-11-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_userpublicationrelation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpublicationrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Not bad'), (4, 'Good'), (5, 'Amazing')], null=True),
        ),
    ]
