# Generated by Django 3.2.9 on 2021-11-13 12:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_userpublicationrelation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
