# Generated by Django 3.2.9 on 2021-11-13 12:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_publication_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpublicationrelation',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, max_length=3000),
        ),
    ]
