# Generated by Django 3.2.9 on 2021-11-13 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_alter_publication_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userpublicationrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Not bad'), (4, 'Good'), (5, 'Amazing')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userpublicationrelation',
            unique_together={('user', 'publication')},
        ),
    ]
