# Generated by Django 3.2.9 on 2021-11-14 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_auto_20211113_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comment', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Not bad'), (4, 'Good'), (5, 'Amazing')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='readers',
        ),
        migrations.AlterField(
            model_name='publication',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='UserPublicationRelation',
        ),
        migrations.AddField(
            model_name='rate',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.publication'),
        ),
        migrations.AddField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.publication'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'publication')},
        ),
    ]
