# Generated by Django 3.2.9 on 2021-11-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_publication_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(default='Tag description', max_length=1000),
        ),
    ]
