# Generated by Django 3.2.9 on 2021-12-02 00:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_group_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_en',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_ru',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='name_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
