# Generated by Django 3.2.9 on 2021-12-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20211202_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_en',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_ru',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_name_en',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_name_ru',
        ),
        migrations.AddField(
            model_name='publication',
            name='lang',
            field=models.CharField(default='en', max_length=64),
        ),
    ]
