# Generated by Django 3.2.9 on 2021-12-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='lang',
            field=models.SmallIntegerField(choices=[(1, 'en-us'), (2, 'ru')], default='en-us'),
        ),
    ]
