# Generated by Django 3.2.9 on 2021-12-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_publication_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='lang',
            field=models.SmallIntegerField(choices=[(0, 'en'), (1, 'ru')], default='en-us'),
        ),
    ]
