# Generated by Django 3.2.9 on 2021-12-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_publication_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='slug',
        ),
    ]
