# Generated by Django 3.2.9 on 2021-12-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_publication_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='lang',
        ),
    ]
