# Generated by Django 3.2.9 on 2021-12-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_publication_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pictures',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
